services:
    redis:
        image: redis:7-alpine
        container_name: xoniapp-redis
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        networks:
            - xoniaapp

    postgres:
        image: postgres:16-alpine
        container_name: xoniapp-postgres
        environment:
            - NODE_ENV=${NODE_ENV}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_URL=postgresql://manager:${POSTGRES_PASSWORD}@postgres:5432/db
            - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
            - ORIGIN=${ORIGIN}
            - AES_SECRET=${AES_SECRET}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        networks:
            - xoniaapp

    app:
        build: .
        container_name: xoniapp-server
        env_file:
            - .env
        ports:
            - '5000:5000'
        depends_on:
            - redis
            - postgres
        restart: always
        networks:
            - xoniaapp

volumes:
    redis-data:
    postgres-data:

networks:
    xoniaapp:
        name: xoniaapp
